server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/navgrowdevdb
spring.datasource.username=navgrow_user
spring.datasource.password=Navgrow@jul25
spring.jpa.hibernate.ddl-auto=update